// Package rnote provides a parser for GitHub release notes generated by GitHub API.
package rnote

import (
	"strconv"
	"strings"
)

type ReleaseNote struct {
	PullRequests     []*PullRequest
	FullChangelogURL string
	NewContributors  []*Contributor
}

type Contributor struct {
	Login          string
	PullRequestURL string
	PullRequest    *PullRequest
}

type PullRequest struct {
	Number int
	URL    string
	Title  string
	Author string
}

// The format of the release note body is as follows:
// ## What's Changed
// * <PR title> by @<PR author> in <PR URL>
//
// ## New Contributors
// * @<pr author> made their first contribution in <PR URL>
//
// **Full Changelog**: <compare URL>

const (
	headerWhatsChanged    = "## What's Changed"
	headerNewContributors = "## New Contributors"
	prefixFullChangelog   = "**Full Changelog**:"
	contributorMarker     = " made their first contribution in "
	prURLMarker           = "/pull/"
)

type section int

const (
	sectionNone section = iota
	sectionChanges
	sectionContributors
)

// Parse parses a release note body and returns a ReleaseNote struct.
func Parse(body string) *ReleaseNote {
	rn := &ReleaseNote{}
	sec := sectionNone
	for raw := range strings.SplitSeq(body, "\n") {
		sec = processLine(strings.TrimRight(raw, "\r"), sec, rn)
	}
	linkContributors(rn)
	return rn
}

func processLine(line string, sec section, rn *ReleaseNote) section {
	switch {
	case line == headerWhatsChanged:
		return sectionChanges
	case line == headerNewContributors:
		return sectionContributors
	case strings.HasPrefix(line, "## "):
		return sectionNone
	case strings.HasPrefix(line, prefixFullChangelog):
		rn.FullChangelogURL = strings.TrimSpace(strings.TrimPrefix(line, prefixFullChangelog))
		return sectionNone
	case strings.HasPrefix(line, "* "):
		appendListItem(line, sec, rn)
	}
	return sec
}

func appendListItem(line string, sec section, rn *ReleaseNote) {
	switch sec {
	case sectionChanges:
		if pr := parsePRLine(line); pr != nil {
			rn.PullRequests = append(rn.PullRequests, pr)
		}
	case sectionContributors:
		if c := parseContributorLine(line); c != nil {
			rn.NewContributors = append(rn.NewContributors, c)
		}
	}
}

func linkContributors(rn *ReleaseNote) {
	byURL := make(map[string]*PullRequest, len(rn.PullRequests))
	for _, pr := range rn.PullRequests {
		if pr.URL != "" {
			byURL[pr.URL] = pr
		}
	}
	for _, c := range rn.NewContributors {
		c.PullRequest = byURL[c.PullRequestURL]
	}
}

// parsePRLine parses a line like "* <title> by @<author> in <url>".
func parsePRLine(line string) *PullRequest {
	rest := strings.TrimPrefix(line, "* ")
	inIdx := strings.LastIndex(rest, " in ")
	if inIdx < 0 {
		return nil
	}
	url := strings.TrimSpace(rest[inIdx+len(" in "):])
	left := rest[:inIdx]
	byIdx := strings.LastIndex(left, " by @")
	if byIdx < 0 {
		return nil
	}
	title := left[:byIdx]
	author := left[byIdx+len(" by @"):]
	return &PullRequest{
		Number: prNumberFromURL(url),
		URL:    url,
		Title:  title,
		Author: author,
	}
}

// parseContributorLine parses a line like "* @<login> made their first contribution in <url>".
func parseContributorLine(line string) *Contributor {
	rest := strings.TrimPrefix(line, "* ")
	if !strings.HasPrefix(rest, "@") {
		return nil
	}
	rest = strings.TrimPrefix(rest, "@")
	login, url, ok := strings.Cut(rest, contributorMarker)
	if !ok {
		return nil
	}
	return &Contributor{
		Login:          login,
		PullRequestURL: strings.TrimSpace(url),
	}
}

// prNumberFromURL extracts the numeric PR id from a URL like
// "https://github.com/owner/repo/pull/123". Returns 0 if not parseable.
func prNumberFromURL(url string) int {
	idx := strings.LastIndex(url, prURLMarker)
	if idx < 0 {
		return 0
	}
	tail := url[idx+len(prURLMarker):]
	if slash := strings.IndexAny(tail, "/?#"); slash >= 0 {
		tail = tail[:slash]
	}
	n, err := strconv.Atoi(tail)
	if err != nil {
		return 0
	}
	return n
}
